### ISSUE TITLE
ahoy throws error after running starter script

### ISSUE THREAD

**Issue by richardgaunt** [drevops/vortex#1551]
Minor issue

## Steps to reproduce
1. Run the installation script
2. run the `ahoy` command to see commands
3. Receive `[fatal] Command [local] has 'imports' set, but no commands were found. Check your yaml file.`

## Cause
`.ahoy.local.example.yml` is created but not `.ahoy.local.yml` and so ahoy cannot find the local file to import commands and throws this error.

## Proposed fix

Change installation script to create a `.ahoy.local.yml` rather than an example file

**Comment by richardgaunt** [comment]
I can see why it's done this way `.ahoy.local.yml` is excluded via `.gitignore` so your local commands are not added to repository.

But equally it's referred to via `.ahoy.yml` so it is a file that needs to be added to repository or else every developer needs to create this file. 

I guess there needs to be  a direction on whether this local file is created when you install or change the .gitignore so it is added to the repository which defeats the `local` aspect of the ahoy file or request change with ahoy to make it a warning rather than an error

**Comment by AlexSkrypnyk** [comment]
Could you please check the version of Ahoy you are using.

```
  local:
    usage: Custom local commands. See `ahoy local help`.
    optional: true <---- This option was added recently
    imports:
      - .ahoy.local.yml
```
