### ISSUE TITLE
Add Drush aliases for prod/stage/dev

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drevops/vortex#1669]
```
production:
  host: ssh.lagoon.amazeeio.cloud
  user: <populated-by-installer>
  root: <populated-by-installer> (could be `/app/web` or `/app/docroot` or be missing for Acquia
  uri: https://<populated-by-installer>
  ssh:
    options: "-p 32222 -o 'UserKnownHostsFile=/dev/null' -o 'StrictHostKeyChecking=no'"
stage:
  host: ssh.lagoon.amazeeio.cloud
  user: <populated-by-installer>
  root: <populated-by-installer> (could be `/app/web` or `/app/docroot` or be missing for Acquia
  uri: https://<populated-by-installer>
  ssh:
    options: "-p 32222 -o 'UserKnownHostsFile=/dev/null' -o 'StrictHostKeyChecking=no'"
dev:
  host: ssh.lagoon.amazeeio.cloud
  user: <populated-by-installer>
  root: <populated-by-installer> (could be `/app/web` or `/app/docroot` or be missing for Acquia
  uri: https://<populated-by-installer>
  ssh:
    options: "-p 32222 -o 'UserKnownHostsFile=/dev/null' -o 'StrictHostKeyChecking=no'"
```
