### ISSUE TITLE
SSL certificate errors in database operations with self-signed certificates in Lagoon environments

### ISSUE THREAD

**Issue by ivangrynenko** [drevops/vortex#1763]
## Summary

Vortex projects deployed in Lagoon environments with self-signed SSL certificates encounter database operation failures during provisioning, specifically with `drush sql:drop` and `drush sql:cli` commands.

## Error Details

**Error Message:**
```
ERROR 2026 (HY000): TLS/SSL error: self-signed certificate in certificate chain

In Process.php line 269:
                                                                               
  The command "mariadb --defaults-file=/tmp/drush_aOhDMc --database=drupal --  
  host=database --port=3306 -A" failed.                                        
                                                                               
  Exit Code: 1(General error)
```

**Affected Operations:**
- `drush sql:drop` in provision.sh (lines 138, 165)
- `drush sql:cli` for database import in provision.sh (line 140)
- Other SQL operations in environments with self-signed certificates

## Root Cause

1. **Drush creates temporary defaults files** (`--defaults-file=/tmp/drush_*`) that override SSL configuration
2. **Direct MariaDB/MySQL calls** bypass Drush configuration files (drush.yml, lagoon.site.yml)
3. **Self-signed certificates** in Lagoon environments cause SSL verification failures
4. **Missing explicit SSL parameters** in critical database operations

## Environment Details

- **Hosting**: Lagoon environments (Amazee.io, Salsa Digital hosting)
- **Database**: MariaDB with self-signed SSL certificates
- **Drush Version**: 13.x
- **Affected Scripts**: `scripts/vortex/provision.sh`, database operations

## Impact

- **CI/CD failures** in GitHub Actions and other CI environments
- **Deployment pipeline breaks** during database provisioning
- **Local development issues** in some Docker configurations
- **Inconsistent behavior** across different hosting environments

### Option 1: Explicit SSL Parameters (Recommended)

Add explicit SSL disabling to affected drush commands in `scripts/vortex/provision.sh`:

```bash
# Line 138
drush sql:drop --extra="--ssl=0"

# Line 140  
drush sql:cli --extra="--ssl=0" <"${VORTEX_DB_DIR}/${VORTEX_DB_FILE}"

# Line 165
drush sql:drop --extra="--ssl=0" || true
```

### Option 2: Enhanced Drush Configuration

**Update `drush/drush.yml`:**
```yaml
sql:
  dump:
    options:
      extra-dump: '--no-tablespaces --ssl=0'
  cli:
    options:
      extra: '--ssl=0'
  connect:
    options:
      extra: '--ssl=0'
  drop:
    options:
      extra: '--ssl=0'
  query:
    options:
      extra: '--ssl=0'
```

**Update `drush/sites/lagoon.site.yml`:**
```yaml
command-specific:
  sql-sync:
    no-ordered-dump: true
    ssl: false
  sql-dump:
    extra-dump: '--no-tablespaces --ssl=0'
  sql-cli:
    extra: '--ssl=0'
  sql-connect:
    extra: '--ssl=0'
  sql-drop:
    extra: '--ssl=0'
  sql-query:
    extra: '--ssl=0'
```

### Option 3: Database Client Configuration

**Update `.docker/config/database/my.cnf`:**
```ini
[client]
# Disable SSL for all client connections to avoid self-signed certificate issues
ssl=false

[mysql]
# Disable SSL for mysql client
ssl=false

[mariadb]
# Disable SSL for mariadb client  
ssl=false

[mysqldump]
# Disable SSL for mysqldump
ssl=false
```

## Proposed Solution

The issue should be addressed in the core Vortex template by:

1. **Adding explicit SSL parameters** to database operations in provision.sh
2. **Enhancing default drush configuration** to include comprehensive SSL settings
3. **Adding database client configuration** for SSL disabling
4. **Documenting the issue** and workarounds for Lagoon deployments

## References

- **Working Example**: https://github.com/salsadigitalauorg/monorepo-vortex/pull/7
- **Previous SSL Fixes**: https://github.com/salsadigitalauorg/monorepo-vortex/pull/4
- **Related Documentation**: [Salsa Digital SSL Certificate Fix Guide](https://salsadigital.atlassian.net/wiki/spaces/SUPPORT/pages/3758653465/Fixing+TLS+SSL+Certificate+Verification+Errors+in+Lagoon+Database+Backups)

## Environment

- **Vortex Version**: Latest (25.3.0+)
- **Hosting**: Lagoon (Amazee.io, Salsa Digital)
- **Database**: MariaDB with self-signed certificates
- **CI/CD**: GitHub Actions, other CI systems

## Additional Context

This issue affects multiple organizations using Vortex with Lagoon hosting and appears to be a common problem in environments with self-signed SSL certificates. The workarounds have been tested and proven effective in production environments.

**Comment by ivangrynenko** [comment]
## ✅ **SOLUTION CONFIRMED** - Complete Working Fix

This issue has been **successfully resolved** in production CI/CD pipelines. Here is the complete, tested solution that addresses all SSL certificate errors in Vortex database operations.

## 🔧 Complete Working Solution

### 1. **Critical Script Modifications**

**File: `scripts/vortex/provision.sh`**
```bash
# Lines 138, 140, 165 - Add explicit SSL parameters to database operations
drush sql:drop --extra="--ssl=0"
drush sql:cli --extra="--ssl=0" <"${VORTEX_DB_DIR}/${VORTEX_DB_FILE}"
drush sql:drop --extra="--ssl=0" || true
```

**File: `scripts/vortex/provision-sanitize-db.sh`**
```bash
# Lines 45, 53, 58-59, 64 - Add SSL parameters to all sql:query operations
drush sql:query --extra="--ssl=0" "UPDATE \`users_field_data\` set users_field_data.name=users_field_data.mail WHERE uid <> '0';"
drush sql:query --extra="--ssl=0" --file="${VORTEX_PROVISION_SANITIZE_DB_ADDITIONAL_FILE/.\//../}"
drush sql:query --extra="--ssl=0" "UPDATE \`users_field_data\` SET mail = '', name = '' WHERE uid = '0';"
drush sql:query --extra="--ssl=0" "UPDATE \`users_field_data\` SET name = '' WHERE uid = '0';"
drush sql:query --extra="--ssl=0" "UPDATE \`users_field_data\` SET mail = '${DRUPAL_ADMIN_EMAIL:-}' WHERE uid = '1';"
```

⚠️ **Important Note**: `drush sql:sanitize` does NOT accept `--extra` parameter and must rely on global configuration.

### 2. **Enhanced Drush Configuration**

**File: `drush/drush.yml`**
```yaml
sql:
  dump:
    options:
      extra-dump: '--no-tablespaces --ssl=0'
  cli:
    options:
      extra: '--ssl=0'
  connect:
    options:
      extra: '--ssl=0'
  drop:
    options:
      extra: '--ssl=0'
  query:
    options:
      extra: '--ssl=0'
```

**File: `drush/sites/lagoon.site.yml`**
```yaml
command-specific:
  sql-sync:
    no-ordered-dump: true
    ssl: false
  sql-dump:
    extra-dump: '--no-tablespaces --ssl=0'
  sql-cli:
    extra: '--ssl=0'
  sql-connect:
    extra: '--ssl=0'
  sql-drop:
    extra: '--ssl=0'
  sql-query:
    extra: '--ssl=0'
```

### 3. **Global Database Client Configuration**

**File: `.docker/config/database/my.cnf`**
```ini
# Custom configuration for database clients.

[client]
# Disable SSL for all client connections to avoid self-signed certificate issues
ssl=false

[mysql]
# Disable SSL for mysql client
ssl=false

[mariadb]
# Disable SSL for mariadb client  
ssl=false

[mysqldump]
# Disable SSL for mysqldump
ssl=false
```

## 🚀 **Deployment Results**

**✅ Status**: All database operations now complete successfully in CI/CD pipelines
- Database import operations: **Working**
- Database sanitization operations: **Working**  
- Database export operations: **Working**
- All SQL query operations: **Working**

## 📋 **Implementation Phases Discovered**

The solution required addressing SSL errors in **multiple phases** of the provisioning process:

1. **Phase 1**: Database import (`sql:drop`, `sql:cli`) - **RESOLVED**
2. **Phase 2**: Database sanitization (`sql:query` operations) - **RESOLVED**
3. **Phase 3**: Configuration validation (global MySQL client config) - **RESOLVED**

## 🔍 **Key Technical Insights**

1. **Drush Command Variability**: Not all Drush SQL commands accept the `--extra` parameter
2. **Multi-Layer Approach Required**: Script-level + configuration-level + client-level SSL disabling
3. **Temporary Defaults Files**: Drush creates temporary MySQL configuration files that override global settings
4. **Command-Specific Solutions**: Different Drush commands require different SSL disabling approaches

## 📖 **Complete Implementation Reference**

- **Working Implementation**: https://github.com/salsadigitalauorg/monorepo-vortex/pull/7
- **Commit History**: Shows the iterative discovery and resolution of each phase
- **Tested Environment**: Lagoon (Salsa Digital hosting) with MariaDB self-signed certificates

## 💡 **Recommendation for Vortex Core**

This comprehensive solution should be integrated into the core Vortex template to prevent other organizations from encountering the same SSL certificate issues in Lagoon environments.

**Priority Files for Core Integration**:
1. `scripts/vortex/provision.sh` - Critical database operations
2. `scripts/vortex/provision-sanitize-db.sh` - Sanitization operations  
3. `drush/drush.yml` - Global Drush SSL configuration
4. `.docker/config/database/my.cnf` - Fallback client configuration

This solution ensures **complete SSL certificate compatibility** with Lagoon hosting environments while maintaining all existing functionality.
